services:
  postgres:
    image: postgres:17.2-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
